### Julian Heidecke, Heidelberg University, IWR 
### julian.heidecke@iwr.uni-heidelberg.de or julian.heidecke@gmail.com
###
### This script serves to visualize "population-level" mosquito-pathogen trait 
### temperature response estimates. They were generated by sampling from  
### hierarchical priors determined by the population-level means and 
### between-species (for life-history traits) or between-experiment 
### (for pathogen-related traits) standard deviations. These hierarchical
### priors were estimated as part of a Bayesian hierarchical model implemented 
### in STAN. 
###
### The script includes the necessary code to reproduce Figures SI4.1, SI4.2
###

# load libraries
library(ggplot2)
library(cowplot)
library(grid)
library(gridExtra)

# set temperature points at which model outputs were generated on
steps = 0.1
temp <- seq(0, 45, steps)

## EIP

# load fitted model 
EIP_fit <- readRDS("model_fits/EIP_fit.rds")
# extract the population level temperature response samples
EIP_fit_pop <- rstan::extract(EIP_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(EIP_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_EIP <- data.frame(x = temp, y = colMeans(EIP_fit_pop, na.rm = TRUE),
                     ymin = apply(EIP_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                     ymax = apply(EIP_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot EIP vs temperature (expected temperature response in new experiment)
plot_EIP_pop <- ggplot(data = df_EIP, mapping = aes(x = x, y = y,
                                     ymin = ymin, 
                                     ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = "Extr. incubation period (days)") + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 250)) 

## Biting rate

# load fitted model 
biting_fit <- readRDS("model_fits/biting_rate_fit.rds")
# extract the population level temperature response samples
biting_fit_pop <- rstan::extract(biting_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(biting_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_biting <- data.frame(x = temp, y = colMeans(biting_fit_pop, na.rm = TRUE),
                     ymin = apply(biting_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                     ymax = apply(biting_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot biting rate vs temperature (expected temperature response of a new species)
plot_biting_pop <- ggplot(data = df_biting, mapping = aes(x = x, y = y,
                                                    ymin = ymin, 
                                                    ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = expression(paste("Adult biting rate  (days"^{-1},")"))) + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 0.55)) 

## Adult mosquito lifespan

# load fitted model 
lf_fit <- readRDS("model_fits/lifespan_fit.rds")
# extract the population level temperature response samples
lf_fit_pop <- rstan::extract(lf_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(lf_fit)

# introduce cut off at lowest observed temperature (14°C)
for(i in 1:(14/steps)){
  lf_fit_pop[,i] <- lf_fit_pop[,(14/steps+1)]
}

# calculate mean and quantiles from sample and store information in a dataframe
df_lf <- data.frame(x = temp, y = colMeans(lf_fit_pop, na.rm = TRUE),
                        ymin = apply(lf_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                        ymax = apply(lf_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot lifespan vs temperature (expected temperature response of a new species)
plot_lf_pop <- ggplot(data = df_lf, mapping = aes(x = x, y = y,
                                                          ymin = ymin, 
                                                          ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = "Adult lifespan  (days)") + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 220)) 

## Egg development rate

# load fitted model 
dev_egg_fit <- readRDS("model_fits/egg_development_fit.rds")
# extract the population level temperature response samples
dev_egg_fit_pop <- rstan::extract(dev_egg_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(dev_egg_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_dev_egg <- data.frame(x = temp, y = colMeans(dev_egg_fit_pop, na.rm = TRUE),
                    ymin = apply(dev_egg_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                    ymax = apply(dev_egg_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot egg dev. rate vs temperature (expected temperature response of a new species)
plot_dev_egg_pop <- ggplot(data = df_dev_egg, mapping = aes(x = x, y = y,
                                                  ymin = ymin, 
                                                  ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = expression(paste("Egg dev. rate (days"^{-1},")"))) + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 1.5)) 

## Juvenile development rate

# load fitted model 
dev_fit <- readRDS("model_fits/juvenile_development_fit.rds")
# extract the population level temperature response samples
dev_fit_pop <- rstan::extract(dev_fit, permuted=T)$f_new_species
# remove model to save local memory
rm(dev_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_dev <- data.frame(x = temp, y = colMeans(dev_fit_pop, na.rm = TRUE),
                    ymin = apply(dev_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                    ymax = apply(dev_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot juv. dev. rate vs temperature (expected temperature response of a new species)
plot_dev_pop <- ggplot(data = df_dev, mapping = aes(x = x, y = y,
                                                    ymin = ymin, 
                                                    ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = expression(paste("Juv. dev. rate (days"^{-1},")"))) + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 0.25)) 

## Egg viability

# load fitted model 
egg_viability_fit <- readRDS("model_fits/egg_viability_fit.rds")
# extract the population level temperature response samples
egg_viability_fit_pop <- rstan::extract(egg_viability_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(egg_viability_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_egg_viability <- data.frame(x = temp, y = colMeans(egg_viability_fit_pop, na.rm = TRUE),
                           ymin = apply(egg_viability_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                           ymax = apply(egg_viability_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot egg viability vs temperature (expected temperature response of a new species)
plot_egg_viability_pop <- ggplot(data = df_egg_viability, mapping = aes(x = x, y = y,
                                                                ymin = ymin, 
                                                                ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = "Egg viability") + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 1)) 

plot_egg_viability_pop

## Mosquito infection probability

# load fitted model 
infprob_fit <- readRDS("model_fits/infection_probability_fit.rds")
# extract the population level temperature response samples
infprob_fit_pop <- rstan::extract(infprob_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(infprob_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_infprob <- data.frame(x = temp, y = colMeans(infprob_fit_pop, na.rm = TRUE),
                               ymin = apply(infprob_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                               ymax = apply(infprob_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot egg viability vs temperature (expected temperature response of a new species)
plot_infprob_pop <- ggplot(data = df_infprob, mapping = aes(x = x, y = y,
                                                                        ymin = ymin, 
                                                                        ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = "Mosq. infection probability") + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 1)) 

## Juvenile survival

# load fitted model 
sur_fit <- readRDS("model_fits/juvenile_survival_fit.rds")
# extract the population level temperature response samples
sur_fit_pop <- rstan::extract(sur_fit, permuted=T)$f_new_spec
# remove model to save local memory
rm(sur_fit)

# calculate mean and quantiles from sample and store information in a dataframe
df_sur <- data.frame(x = temp, y = colMeans(sur_fit_pop, na.rm = TRUE),
                           ymin = apply(sur_fit_pop, 2, function(x) quantile(x, probs = 0.025, na.rm = TRUE)),
                           ymax = apply(sur_fit_pop, 2, function(x) quantile(x, probs = 0.975, na.rm = TRUE)))

# population-level plot egg viability vs temperature (expected temperature response of a new species)
plot_sur_pop <- ggplot(data = df_sur, mapping = aes(x = x, y = y,
                                                                ymin = ymin, 
                                                                ymax = ymax)) +
  geom_line(linewidth = 0.8, col = "red") +
  geom_ribbon(fill="red", alpha=0.15) +
  labs(title = "", x = "Temperature (°C)", y = "Juvenile survival") + 
  theme_bw() +
  theme(plot.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  coord_cartesian(ylim = c(0, 1)) 

# plot all population-level temperature response estimates of the mosquito life-history
# traits together (Figure SI4.1)
plot_list = list(plot_dev_pop, plot_sur_pop, plot_lf_pop, 
                 plot_egg_viability_pop, plot_biting_pop, plot_dev_egg_pop)

plot_grid = cowplot::plot_grid(plotlist = plot_list, ncol=2, 
                               align = "h", axis = "b", labels = c('A','B',
                                                                   'C','D',
                                                                   'E','F'))

x.grob <- textGrob("Temperature (°C)", 
                   gp=gpar(col="black", fontsize=14))

#pdf("Figures/population_level_life_history.pdf", width=8.27, height=9.27)
grid.arrange(arrangeGrob(plot_grid, bottom = x.grob))
#dev.off()

# plot all population-level temperature response estimates of the pathogen-related
# traits together (Figure SI4.2)
plot_list = list(plot_infprob_pop, plot_EIP_pop)

plot_grid = cowplot::plot_grid(plotlist = plot_list, ncol=2, 
                               align = "h", axis = "b", labels = c('A','B'))

x.grob <- textGrob("Temperature (°C)", 
                   gp=gpar(col="black", fontsize=14))

#pdf("Figures/population_level_pathogen_related.pdf", width=8.27, height=3.5)
grid.arrange(arrangeGrob(plot_grid, bottom = x.grob))
#dev.off()

